name: Enviar resumen diario

on:
  schedule:
    # Todos los días a las 11:00 UTC
    - cron: "0 11 * * *"

  # Permite ejecutarlo manualmente
  workflow_dispatch:

jobs:
  enviar-resumen:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar al backend
        run: |
          curl -X POST https://sistemast.onrender.com/tareas/enviar-resumen
